### ISSUE TITLE
Who do I fike a bug report with.

### ISSUE THREAD

**Issue by smith901** [StocksExchange/Android-app#1]
Found a bug. Need to know the proper way to submit so devs can fix.

**Comment by mars885** [comment]
@smith901 Hello. Unfortunately, we do not have any rules to adhere on how to submit the bug, so please describe it here and we will do our best to fix it as soon as possible.

As a matter of fact, we have been working hard on a major update for a long time therefore updated the code today. Since the code has been largely improved and some parts have been rewritten completely, the bug you're mentioning might still be present, so please let us know in that case.

We plan to create releases for every major and minor update we have to retain the code of them, but that will require deleting some files in really old commits that were not supposed to be committed.
When will it happen? I can't tell you exactly, but stay tuned.

As a side note, Github, for some odd reason, has not notified me about this issue the day it was opened, but better later than never.

**Comment by smith901** [comment]
I got the runaround from support. They saw the issue then escalated, then replied no problems. I do have proof. I'm considering my coins lost/stolen and leaving it at that.

For the record, the website wallet addresses and the app wallet addresses were different for some coins. Didn't find out until after sending and the balance didn't  increase after 8hours. No problems until you guys started the system update. Website and app wallet addresses became the same again shortly after informing of the problem. That is when I was notified that there was no problem.

I just want to delete my account with you guys. No a link for that on the site.

**Comment by mars885** [comment]
@smith901 That's sad to hear. As far as I can tell, some guy reported that bug through the email a long time ago and it has been fixed ever since.
